# -*- coding: utf-8 -*-
"""hf_text_classifcation_tutorial.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jmuKvwPGlzrqr0NJbgudaeENkFXBEA6o
"""

from google.colab import userdata
HF_TOKEN = userdata.get('colab_hf_token')

if HF_TOKEN is None:
  print("No HF token found")
else:
  print("Found HF token")

import huggingface_hub

# Login to Hugging Face
huggingface_hub.login(token=HF_TOKEN)

"""# Hugging Face text classification

### 2. Import libraries
"""

# Install dependencies (this is mostly for Google Colab, as the other dependences are available by default in Colab)
try:
  import datasets, evaluate, accelerate
  import gradio as gr
except ModuleNotFoundError:
  !pip install datasets evaluate accelerate gradio # -U stands for "upgrade" so we'll get the latest version by default
  import datasets, evaluate, accelerate
  import gradio as gr

import random

import numpy as np
import pandas as pd

import torch
import transformers

print(f"Using transformers version: {transformers.__version__}")
print(f"Using datasets version: {datasets.__version__}")
print(f"Using torch version: {torch.__version__}")

"""## 3. Getting a dataset"""

from datasets import load_dataset

dataset = load_dataset(path="mrdbourke/learn_hf_food_not_food_image_captions")
dataset

dataset.column_names

dataset["train"]

dataset["train"][0]

"""### Inspect random samples"""

import random
random_index = random.sample(range(len(dataset["train"])), 5)
print(random_index)

random_samples = dataset["train"][random_index]
print("===============")
for text, label in zip(random_samples["text"], random_samples["label"]):
  print(f"[Text] : {text} | [Label] : {label}")

# Get unique label values
dataset["train"].unique("label")

# check count of each label
from collections import Counter

Counter(dataset["train"]["label"])

# Turn dataset to to dataframe
food_not_food_df = pd.DataFrame(dataset["train"])
food_not_food_df.sample(7)

food_not_food_df.value_counts("label")

"""## 4. Preparing data for text classification
1. Tokenize our text - Turn text into numbers
2. Create train/test split
"""

# Create a mapping for labels to numeric value
id2label = {0: "not_food", 1:"food"}
label2id = {"not_food":0 , "food":1}

# create mapping from dataset
id2label = {idx: label for idx, label in enumerate(dataset["train"].unique("label"))}
id2label

label2id = {label: idx for idx,label in enumerate(dataset["train"].unique("label"))}
label2id

# Turn labels to 0 or 1
def map_labels_to_number(example):
  example["label"] = label2id[example["label"]]
  return example

example_sample = {
    "text": "My favourite food is honey",
    "label": "food"

  }
map_labels_to_number(example_sample)

dataset = dataset["train"].map(map_labels_to_number)
dataset[:5]

dataset.shuffle()[:5]

"""### split data to train/test
* Train set : Model will learn patterns on this dataset
* Validation set(optional)
* Test set

Split using `datasets.Dataset.train_test_split()`
"""

dataset = dataset.train_test_split(test_size=0.2,seed=42)
dataset

dataset

random_idx_train = random.randint(0,len(dataset['train']))
random_sample_train = dataset["train"][random_idx_train]
random_sample_train

random_idx_test = random.randint(0,len(dataset["test"]))
random_sample_test = dataset["test"][random_idx_test]
random_sample_test

"""### Tokenizing our text data
Turn words into numbers.

E.g. "I love pizza!" ➡ [30,12,54,89,009]

"""

from transformers import AutoTokenizer
tokenizer =  AutoTokenizer.from_pretrained(
    pretrained_model_name_or_path = "distilbert/distilbert-base-uncased",
    use_fast = True
)
tokenizer

tokenizer("I love Pizza!")

"""

*   `input_ids` : Our text turned into Numbers
*   `attention_mask` : whether or not to pay attention to certain tokens(1= yes pay attention,0=No dont pay attention)

"""

# get the length of our tokenizer
length_of_tokenizer_vocab = len(tokenizer.vocab)
print(f"[INFO] Number of items in tokenizer vocab: {length_of_tokenizer_vocab}")

max_tokenizer_input_sequence_length = tokenizer.model_max_length
print(f"[INFO] Max tokenizer input sequene length: {max_tokenizer_input_sequence_length}")

tokenizer("**Pawara**")

tokenizer.convert_ids_to_tokens(tokenizer("**Pawara**").input_ids)

def tokenize_text(examples):
  """
  Tokenize given example text and return the tokenize text
  """
  return tokenizer(examples["text"],
                   padding=True,
                   truncation=True)

example_sample_2 = {"text": "I love Taco",
"label":1}
tokenize_text(example_sample_2)

tokenized_dataset = dataset.map(
    function=tokenize_text,
    batched=True,
    batch_size=1000
)
tokenized_dataset

train_tokenized_sample = tokenized_dataset["train"][0]
test_tokenized_sample = tokenized_dataset["test"][0]

for key in train_tokenized_sample.keys():
  print(f"[INFO] Key: {key}")
  print(f"Train sample: {train_tokenized_sample[key]}")
  print(f"Test sample: {test_tokenized_sample[key]}")
  print("\n")

"""## Setting up and evaluation metrics

Use evaluation metric to get a numerical idea of how our model is performing.

Some common evlaution metrics for classification.
- Accuracy
- Precision
- Recall
- F1 Score
"""

import evaluate
import numpy as np
from typing import Tuple, Dict

accuracy_metric = evaluate.load("accuracy")

def compute_accuracy(predictions_and_labels: Tuple[np.array, np.array]) :
  """
  Computes the accuracy of a model by comparing the predictions and labels.
  """
  predictions, labels = predictions_and_labels

  return accuracy_metric.compute(predictions=predictions, references=labels)

example_predictions_all_correct = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
example_predictions_one_wrong = np.array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])
example_labels = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

print(f"Accuracy when all predictions are correct: {compute_accuracy((example_predictions_all_correct, example_labels))}")
print(f"Accuracy when one prediction is wrong: {compute_accuracy((example_predictions_one_wrong, example_labels))}")

## Fixing bug
import evaluate
import numpy as np
from typing import Tuple, Dict

accuracy_metric = evaluate.load("accuracy")

def compute_accuracy(predictions_and_labels: Tuple[np.array, np.array]) :
  """
  Computes the accuracy of a model by comparing the predictions and labels.
  """
  predictions, labels = predictions_and_labels

  if len(predictions.shape) >= 2:
    predictions = np.argmax(predictions,axis=1)

  return accuracy_metric.compute(predictions=predictions, references=labels)

"""## Setting up a model for trainning

* Use transfer learning

Workflow for training
* Create and pre-process data
* Define model
* Define trainning arguments `trandformers.TrainingArguments`
* Pass `TrainingArguments` to an instance of `transformer.Trainer`
* Train model
* Save model
* Evaluate model
"""

from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained(
    pretrained_model_name_or_path = "distilbert/distilbert-base-uncased",
    num_labels=2,
    id2label= id2label,
    label2id= label2id
)

model

"""Our model is comprised with following parts:

1. `embeddings` - embeddings are a form of learned representation of tokens.
2. `transformer` - Model architecture backbone, this has discovered patterns/relationships in the embedding.
3. `classifier`

### Count paramters in the model

Weights/parameters = small numeric opportunities for a model to learn pattersn in data.
"""

def count_params(model) -> Dict:
  trainable_params = sum(params.numel() for params in model.parameters() if params.requires_grad)
  total_params = sum(params.numel() for params in model.parameters())

  return {"trainable_parameters" : trainable_params, "total_parameters": total_params}

count_params(model)

"""Looks like our model has a total of 66,955,010 parameters and all of them are trainable.

A parameter is a numerical value in a model which is capable of being updated to better represent the input data.

I like to think of them as a small opportunity to learn patterns in the data.

If a model has three parameters, it has three small opportunities to learn patterns in the data.

Whereas, if a model has 60,000,000+ (60M) parameters (like our model), it has 60,000,000+ small opportunities to learn patterns in the data.

Some models such as Large Language Models (LLMs) like [Llama 3 70B](https://huggingface.co/meta-llama/Meta-Llama-3-70B) have 70,000,000,000+ (70B) parameters (over 1000x our model).

In essence, the more parameters a model has, the more opportunities it has to learn (generally).

More parameters often results in more capabilities.

However, more parameters also often results in a much larger model size (e.g. many gigabytes versus hundreds of megabytes) as well as a much longer compute time (fewer samples per second).

For our use case, a binary text classification task, 60M parameters is more than enough.

## Createa directory for saving the model
"""

from pathlib import Path

models_dir = Path("models")
models_dir.mkdir(exist_ok=True)

model_save_name = "learn_hf_food_not_food_text_classifier-distilbert-base-uncased"

model_save_dir = Path(models_dir, model_save_name)
model_save_dir

"""### Settings to be adjust

1. ✅ Create and preprocess data.
2. ✅ Define the model we’d like use with `transformers.AutoModelForSequenceClassification` (or another similar model class).
3. Define training arguments (these are hyperparameters for our model) with `transformers.TrainingArguments`.
4. Pass TrainingArguments from 3 and target datasets to an instance of `transformers.Trainer`.
5. Train the model by calling `Trainer.train()`.
6. Save the model (to our local machine or to the Hugging Face Hub).
7. Evaluate the trained model by making and inspecting predctions on the test data.
8. Turn the model into a shareable demo.
"""

from transformers import TrainingArguments

print(f"[INFO] Saving model checkpoints: {model_save_dir}")

BATCH_SIZE = 32

training_args = TrainingArguments(
    output_dir= model_save_dir,
    learning_rate = 0.0001,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    num_train_epochs=10,
    eval_strategy = "epoch",
    save_strategy = "epoch",
    save_total_limit =3,
    use_cpu=False,
    seed=42,
    load_best_model_at_end=True,
    report_to="none",
    push_to_hub = False,
    hub_private_repo = False
)

training_args

"""### Settings to be adjust

1. ✅ Create and preprocess data.
2. ✅ Define the model we’d like use with `transformers.AutoModelForSequenceClassification` (or another similar model class).
3. ✅ Define training arguments (these are hyperparameters for our model) with `transformers.TrainingArguments`.
4. Pass TrainingArguments from 3 and target datasets to an instance of `transformers.Trainer`.
5. Train the model by calling `Trainer.train()`.
6. Save the model (to our local machine or to the Hugging Face Hub).
7. Evaluate the trained model by making and inspecting predctions on the test data.
8. Turn the model into a shareable demo.
"""

from transformers import Trainer, DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"],
    eval_dataset=tokenized_dataset["test"],
    processing_class=tokenizer,
    data_collator=data_collator,
    compute_metrics=compute_accuracy,
)
trainer

"""### Settings to be adjust

1. ✅ Create and preprocess data.
2. ✅ Define the model we’d like use with `transformers.AutoModelForSequenceClassification` (or another similar model class).
3. ✅ Define training arguments (these are hyperparameters for our model) with `transformers.TrainingArguments`.
4. ✅ Pass TrainingArguments from 3 and target datasets to an instance of `transformers.Trainer`.
5. Train the model by calling `Trainer.train()`.
6. Save the model (to our local machine or to the Hugging Face Hub).
7. Evaluate the trained model by making and inspecting predctions on the test data.
8. Turn the model into a shareable demo.
"""

results = trainer.train()

for key,value in results.metrics.items():
  print(f"{key} : {value}")

## save model
print(f"[INFO] Saving model in {model_save_dir}")
trainer.save_model(output_dir = model_save_dir)

# Get training history
trainer_history_all = trainer.state.log_history
trainer_history_metrics = trainer_history_all[:-1] # get everything except the training time metrics (we've seen these already)
trainer_history_training_time = trainer_history_all[-1] # this is the same value as results.metrics from above

# View the first 4 metrics from the training history
trainer_history_metrics[:4]

import pprint # import pretty print for nice printing of lists

# Extract training and evaluation metrics
trainer_history_training_set = []
trainer_history_eval_set = []

# Loop through metrics and filter for training and eval metrics
for item in trainer_history_metrics:
    item_keys = list(item.keys())
    # Check to see if "eval" is in the keys of the item
    if any("eval" in item for item in item_keys):
        trainer_history_eval_set.append(item)
    else:
        trainer_history_training_set.append(item)

# Show the first two items in each metric set
print(f"[INFO] First two items in training set:")
pprint.pprint(trainer_history_training_set[:2])

print(f"\n[INFO] First two items in evaluation set:")
pprint.pprint(trainer_history_eval_set[:2])

# Create pandas DataFrames for the training and evaluation metrics
trainer_history_training_df = pd.DataFrame(trainer_history_training_set)
trainer_history_eval_df = pd.DataFrame(trainer_history_eval_set)

trainer_history_training_df.head()

trainer_history_eval_df.head()

# Plot training and evaluation loss
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
#plt.plot(trainer_history_training_df["epoch"], trainer_history_training_df["loss"], label="Training loss")
plt.plot(trainer_history_eval_df["epoch"], trainer_history_eval_df["eval_loss"], label="Evaluation loss")
plt.xlabel("Epoch")
plt.ylabel("Loss")
plt.title("Text classification with DistilBert training and evaluation loss over time")
plt.legend()
plt.show()

trainer_history_training_df

"""## Making and evaluating predictions on the test data

1. ✅ Create and preprocess data.
2. ✅ Define the model we’d like use with `transformers.AutoModelForSequenceClassification` (or another similar model class).
3. ✅ Define training arguments (these are hyperparameters for our model) with `transformers.TrainingArguments`.
4. Pass TrainingArguments from 3 and target datasets to an instance of `transformers.Trainer`.
5. ✅ Train the model by calling `Trainer.train()`.
6. ✅ Save the model (to our local machine or to the Hugging Face Hub).
7. Evaluate the trained model by making and inspecting predctions on the test data.
8. Turn the model into a shareable demo.


We can make predictions on the test dataset using `transformers.Trainer.predict`.
"""

prediction_all = trainer.predict(tokenized_dataset["test"])
prediction_values = prediction_all.predictions
prediction_metrics = prediction_all.metrics

print("[INFO] Prediction metrics on the test data:")
prediction_metrics

prediction_all.predictions[0]

import torch
from sklearn.metrics import accuracy_score

pred_probs = torch.softmax(torch.tensor(prediction_values),dim=1)

pred_labels = torch.argmax(pred_probs, dim=1)

# Get the true labels
true_labels = dataset["test"]["label"]

# compute prediction labels to true labels and get test accuracy
test_accuracy = accuracy_score(y_true=true_labels,
                               y_pred=pred_labels
                               )
print(f"[INFO] The test accuracy is {test_accuracy*100}%")

"""### Exploring prediction probabilities

It's very good way to evaluate a model by sorting predictions probabilities and seeing where the model went wrong.
"""

# Make a DataFrame of test predictions
test_predictions_df = pd.DataFrame({
    "text": dataset["test"]["text"],
    "true_label": true_labels,
    "pred_label": pred_labels,
    "pred_prob": torch.max(pred_probs, dim=1).values
})

test_predictions_df.head()

test_predictions_df.sort_values("pred_prob",ascending=True).head(10)

"""## Making and inspecting predictions on custom text data

### Discussing the wasy to make predictions

1. **Pipeline mode** - Using `transformer.pipeline` method to perform classification. See docs: https://huggingface.co/docs/transformers/en/main_classes/pipelines
2. **Pytorch mode** - Using combination os `transformer.AutoTokeinizer` and `transformers.AutoModelForSequenceClassification`

1. Each mode supports one preiction at a time
2. Support batches of predictions. - Faster
"""

local_model_path = "/content/models/learn_hf_food_not_food_text_classifier-distilbert-base-uncased"
huggingface_model_path = ""

